### ISSUE TITLE
Error on launch 1.0.9

### ISSUE THREAD

**Issue by BuckShotSX** [sbroenne/plugin.video.nhkworldtv#89]
Hi
I am getting error on launch of the new plugin.   After the error I have launched other plugins successfully, and restarted Kodi, and still the error.

Environment:
NHK World TV 1.0.9
Windows 10 21H2 (kernel: Windows NT 10.0.19044.1889)
Kodi 19.3.0

From the Log file:
2022-09-09 11:08:33.532 T:3368    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: object of type 'NoneType' has no len()
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nhkworldtv\main.py", line 1, in <module>
                                                       from lib import plugin
                                                     File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nhkworldtv\lib\plugin.py", line 11, in <module>
                                                       from . import (
                                                     File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nhkworldtv\lib\vod.py", line 18, in <module>
                                                       EPISODE_CACHE = cache_api.get_program_metdadata_cache()
                                                     File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nhkworldtv\lib\cache_api.py", line 29, in get_program_metdadata_cache
                                                       f"cache_api.get_program_metdadata_cache: Got {len(cache)} episodes from Azure CDN"
                                                   TypeError: object of type 'NoneType' has no len()
                                                   -->End of Python script error report<--

I have looked at the cache_api.py and only noticed the url is:
 cache_file = "https://nhkworldtv.azureedge.net/program-list-v2/cache.json"

Which is the same as previous versions.

But I can't nslookup nhkworldtv.azureedge.net:

C:\Users\antho>nslookup nhkworldtv.azureedge.net
Server:  Netgear
Address:  192.168.0.1

*** Netgear can't find nhkworldtv.azureedge.net: Non-existent domain

But this I can:
C:\Users\antho>nslookup nhkworldtv.azuredge.net
Server:  Netgear
Address:  192.168.0.1

Non-authoritative answer:
Name:    nhkworldtv.azuredge.net
Addresses:  2600:3c02::f03c:91ff:fee2:5b0f
          67.227.226.240

Like I said, this was what it was in 1.0.8 as well.
I went to the Plugin Settings and went to Caching and set:

Use episode URL cache from Azure CDN (recommended) - Disabled

The plugin launches.

**Comment by sbroenne** [comment]
@BuckShotSX : Thanks for reporting this. I moved the backend cache to a new Azure Subscription, and it seems that the CDN endpoint did not start automatically after the move. Everything is back to normal now and you can re-enable the cache!

I will add better error handling for this situation to the add-on in the future.
