### ISSUE TITLE
Error on launch of plugin.

### ISSUE THREAD

**Issue by BuckShotSX** [sbroenne/plugin.video.nhkworldtv#94]
Hi,
It looks like the NHK World Live Website has been changed and I think that's the root cause.    I believe the change was on March 23, 23.

How to reproduce;
Launch the plugin.  It is not opening and erroring out.

System:
Windows 10 21H2
Kodi Build 20.1
Plugin version 1.0.9

Part of the error.log;

2023-03-23 10:32:30.469 T:2444     info <Platinum>: [neptune.sockets.bsd]: connecting to 192.168.0.172, port 52559
2023-03-23 10:32:30.679 T:5852     info <general>: Skipped 1 duplicate messages..
2023-03-23 10:32:30.679 T:5852  warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-03-23 10:32:30.679 T:5852  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-03-23 10:32:30.758 T:5852    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: argument of type 'NoneType' is not iterable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nhkworldtv\main.py", line 6, in <module>
                                                       plugin.run()
                                                     File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nhkworldtv\lib\plugin.py", line 66, in run
                                                       plugin.run()
                                                     File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nhkworldtv\lib\plugin.py", line 80, in index
                                                       add_ataglance_menu_item()
                                                     File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nhkworldtv\lib\plugin.py", line 175, in add_ataglance_menu_item
                                                       menu_item = ataglance.get_menu_item()
                                                     File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nhkworldtv\lib\ataglance.py", line 21, in get_menu_item
                                                       menu_item.thumb = thumbnails["list_sp"]
                                                     File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nhkworldtv\lib\episode.py", line 124, in thumb
                                                       if "/nhkworld/" in value and not self.absolute_image_url:
                                                   TypeError: argument of type 'NoneType' is not iterable
                                                   -->End of Python script error report<--
                                                   
2023-03-23 10:32:31.429 T:8624    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.nhkworldtv/
2023-03-23 10:32:31.459 T:3868    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nhkworldtv/) failed
2023-03-23 10:32:31.478 T:5024     info <Platinum>: [platinum.inputdatagramstream]: PLT_InputDatagramStream received 174
2023-03-23 10:32:31.479 T:5024     info <Platinum>: [platinum.inputdatagramstream]: PLT_InputDatagramStream requested 4096, consumed 174, left 0
2023-03-23 10:32:31.479 T:5024     info <Platinum>: [platinum.core.devicehost]: PLT_DeviceHost::OnSsdpPacket M-SEARCH for urn:dial-multiscreen-org:service:dial:1 from 192.168.0.172:52559
M-SEARCH * HTTP/1.1

**Comment by xyzy-web** [comment]
I get the same error on Kodi 19.5

**Comment by sbroenne** [comment]
@BuckShotSX , @xyzy-web: I am working on a new version that will fix these issues.

**Comment by sbroenne** [comment]
@BuckShotSX : I have uploaded a new version of the repository that works for Nexus. This repo will then allow you to update the plug-in to 1.0.11 which fixes the start-up issue.

Unfortunately, the repo does not update itself so you need download & install it yourself.

https://bit.ly/3ZCz8b8

or

https://github.com/sbroenne/kodirepo/raw/main/repository.sbroenne/repository.sbroenne-0.0.16.zip

**Comment by xyzy-web** [comment]
Hi @sbroenne ,

thanks a lot for fixing the problems, everything is working fine again :-)
